require("dorage.snippets.luasnip.all")
require("dorage.snippets.luasnip.common")
require("dorage.snippets.luasnip.lua")
require("dorage.snippets.luasnip.markdown")
require("dorage.snippets.luasnip.tsserver")
