require("dorage.snippets.luasnip.all")
require("dorage.snippets.luasnip.common")
require("dorage.snippets.luasnip.lua")
require("dorage.snippets.luasnip.markdown")
require("dorage.snippets.luasnip.tsserver")
require("dorage.snippets.luasnip.perl")
require("dorage.snippets.luasnip.react")
